repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  - repo: https://github.com/FalcoSuessgott/mdtmpl
    rev: v0.0.4
    hooks:
      # example
      - id: mdtmpl
        args: [-t=examples/README.md.tmpl, -f, -o=examples/README.md]
        stages: [commit-msg]
      # readme
      - id: mdtmpl
        args: [-f]
        stages: [commit-msg]
